### ISSUE TITLE
Can you share the source code of "Wav2LogSpec.exe“"?

### ISSUE THREAD

**Issue by kjxijk** [yongxuUSTC/DNN-for-speech-enhancement#15]
Dear Dr. Xu:
Can you share the source code of "Wav2LogSpec.exe“? It would help a lot for us to know how you transfer the .raw file to .lsp file.  And if possible, can you also share the source code of "LogSpec2raw_16bit_withoutXF.exe" in the decoding process?

Any help from you would be greatly appreciated!

**Comment by demeng** [comment]
Indeed. Appreciate if you can share the code of "LogSpec2raw_16bit_withoutXF.exe". Thanks!
